name: jitsi_meet_local_platform_interface
description: A common platform interface for the jitsi meet plugin.
version: 1.0.0
homepage: https://github.com/NifalNizar/jitsi_meet_local

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

