name: jitsi_meet_local
description: Jitsi Meet Local Plugin - A plugin for integrating open source Jitsi Meet API in flutter. Jitsi Meet is secure, fully featured and allows completely free video conferencing made with https://jitsi.org, a collection of open source projects
version: 1.0.13
homepage: https://github.com/NifalNizar/jitsi_meet_local

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  jitsi_meet_local_platform_interface: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.advoques.jitsi_meet_local
        pluginClass: JitsiMeetLocalPlugin
      ios:
        pluginClass: JitsiMeetLocalPlugin
