name: jitsi_meet_platform_interface_local
description: A common platform interface for the jitsi meet plugin.
version: 1.0.0
homepage: https://github.com/NifalNizar/jitsi_meet_local

environment:
  sdk: '>=3.0.0 <4.0.0'
  # flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

